# GoReleaser configuration for DaemonEye
# Aligned with dist-workspace.toml configuration

# yaml-language-server: $schema=https://goreleaser.com/static/schema.json

version: 2

project_name: daemoneye

before:
    hooks:
        - rustup default stable
        - cargo install --locked cargo-zigbuild
        - cargo fetch --locked

builds:
    # procmond - Process monitoring daemon
    - builder: rust
      id: procmond
      binary: procmond
      flags:
          - --release
      targets:
          - aarch64-apple-darwin
          - aarch64-unknown-linux-gnu
          - aarch64-pc-windows-msvc
          - x86_64-apple-darwin
          - x86_64-unknown-linux-gnu
          - x86_64-pc-windows-msvc

    # daemoneye-agent - Detection orchestrator
    - builder: rust
      id: daemoneye-agent
      binary: daemoneye-agent
      flags:
          - --release
      targets:
          - aarch64-apple-darwin
          - aarch64-unknown-linux-gnu
          - aarch64-pc-windows-msvc
          - x86_64-apple-darwin
          - x86_64-unknown-linux-gnu
          - x86_64-pc-windows-msvc

    # daemoneye-cli - Command-line interface
    - builder: rust
      id: daemoneye-cli
      binary: daemoneye-cli
      flags:
          - --release
      targets:
          - aarch64-apple-darwin
          - aarch64-unknown-linux-gnu
          - aarch64-pc-windows-msvc
          - x86_64-apple-darwin
          - x86_64-unknown-linux-gnu
          - x86_64-pc-windows-msvc

archives:
    - formats: [tar.xz]
      # Archive naming template matching dist configuration
      name_template: >-
          {{ .ProjectName }}_
          {{- title .Os }}_
          {{- if eq .Arch "amd64" }}x86_64
          {{- else if eq .Arch "386" }}i386
          {{- else }}{{ .Arch }}{{ end }}
      # Include all three binaries in each archive
      files:
          - procmond*
          - daemoneye-agent*
          - daemoneye-cli*
      # Use zip for Windows archives to match dist configuration
      format_overrides:
          - goos: windows
            formats: [zip]

changelog:
    sort: asc
    filters:
        exclude:
            - "^docs:"
            - "^test:"

release:
    github:
        owner: EvilBit-Labs
        name: DaemonEye
    footer: >-
        Successfully installed DaemonEye! Ready to start watching your processes!

        ---

        Released by [GoReleaser](https://github.com/goreleaser/goreleaser).
