coverage:
    status:
        project:
            default:
                target: 85%
                threshold: 2%
        patch:
            default:
                target: 90%
                threshold: 5%
    ignore:
        - "tests/**/*"
        - "benches/**/*"
        - "examples/**/*"
        - "target/**/*"
        - "sentinel/**/*" # Exclude distribution package from coverage
