coverage:
    status:
        project:
            default:
                target: 80%
                threshold: 5%
        patch:
            default:
                target: 70%
                threshold: 10%
    ignore:
        - "tests/**/*"
        - "benches/**/*"
        - "examples/**/*"
        - "target/**/*"
        - "daemoneye/**/*" # Exclude distribution package from coverage
