# Several tools are set to "latest" to ensure they are using the idiomatic version file.
[tools]
cargo-binstall              = "latest"
cargo-insta                 = "1.47.2"
"cargo:cargo-audit"         = "latest"
"cargo:cargo-deny"          = "0.19.8"
"cargo:cargo-llvm-cov"      = "0.8.7"
"cargo:cargo-nextest"       = "0.9.137"
"cargo:mdbook"              = "latest"
"cargo:mdbook-linkcheck"    = "latest"
"cargo:mdbook-tabs"         = "latest"
"cargo:mdbook-mermaid"      = "latest"
"cargo:mdbook-toc"          = "latest"
"cargo:mdbook-admonish"     = "latest"
"cargo:mdbook-open-on-gh"   = "latest"
"cargo:mdbook-i18n-helpers" = "latest"
just                        = "latest"
python                      = "latest"
rust                        = { version = "latest", components = "llvm-tools,cargo,rustfmt,clippy", profile = "default" }
"cargo:cargo-outdated"      = "latest"
"cargo:cargo-release"       = "latest"
"cargo:cargo-auditable"     = "latest"
"cargo:cargo-cyclonedx"     = "latest"
"pipx:mdformat"             = { version = "1.0.0", uvx_args = "--with mdformat-gfm --with mdformat-config --with mdformat-footnote --with mdformat-front-matters --with mdformat-simple-breaks --with mdformat-web --with mdformat-gfm-alerts --with mdformat-toc" }
prettier                    = "latest"
actionlint                  = "latest"
lychee                      = "latest"
markdownlint-cli2           = "latest"
protobuf                    = "latest"
protoc                      = "latest"
zig                         = "latest"
"cargo:cargo-zigbuild"      = "latest"
bun                         = "latest"
goreleaser                  = "latest"
"pipx:pre-commit"           = "latest"
uv                          = "latest"

# Many of these settings are defaults, but we are explicit in case they change in the future and to make it clear to users what is enabled.
[settings]
activate_aggressive                 = true
idiomatic_version_file_enable_tools = [ "python", "rust", "bun", "zig" ]
env_cache                           = true
exec_auto_install                   = true
github_attestations                 = true
lockfile                            = true
minimum_release_age                 = "7d"
pin                                 = false
slsa                                = true

[settings.npm]
package_manager = "bun"

[settings.pipx]
uvx = true
