name: ✨ Feature Request
description: Suggest an idea for DaemonEye
title: "[Feature]: "
labels: ["enhancement", "needs-triage"]
assignees: []

body:
    - type: markdown
      attributes:
          value: |
              Thanks for suggesting a new feature! Please provide as much detail as possible to help us understand your request.

    - type: dropdown
      id: component
      attributes:
          label: Component
          description: Which DaemonEye component would this feature affect?
          options:
              - procmond (Process Collector)
              - daemoneye-agent (Orchestrator)
              - sentinelcli (CLI Interface)
              - sentinel-lib (Shared Library)
              - Documentation
              - Build System
              - Security Center (Business/Enterprise)
              - Cross-component
              - Other
      validations:
          required: true

    - type: dropdown
      id: tier
      attributes:
          label: Feature Tier
          description: Which deployment tier would this feature belong to?
          options:
              - Free Tier (Core functionality)
              - Business Tier ($199/site)
              - Enterprise Tier (Custom pricing)
              - All Tiers
              - Not sure
      validations:
          required: true

    - type: dropdown
      id: priority
      attributes:
          label: Priority
          description: How important is this feature to you?
          options:
              - Low (Nice to have)
              - Medium (Would be helpful)
              - High (Important for my use case)
              - Critical (Blocking my adoption)
      validations:
          required: true

    - type: textarea
      id: problem
      attributes:
          label: Problem Statement
          description: |
              What problem does this feature solve? What is the current limitation or pain point?
          placeholder: "Describe the problem you're trying to solve..."
      validations:
          required: true

    - type: textarea
      id: solution
      attributes:
          label: Proposed Solution
          description: |
              Describe the solution you'd like to see implemented.
          placeholder: "Describe your proposed solution..."
      validations:
          required: true

    - type: textarea
      id: alternatives
      attributes:
          label: Alternative Solutions
          description: |
              Describe any alternative solutions or workarounds you've considered.
          placeholder: "Describe any alternatives you've considered..."

    - type: textarea
      id: usecase
      attributes:
          label: Use Case
          description: |
              Describe your specific use case and how this feature would help.
          placeholder: |
              - Who would use this feature?
              - What workflow would it improve?
              - What are the expected benefits?
      validations:
          required: true

    - type: textarea
      id: acceptance
      attributes:
          label: Acceptance Criteria
          description: |
              What would need to be true for you to consider this feature complete?
          placeholder: |
              - [ ] Criterion 1
              - [ ] Criterion 2
              - [ ] Criterion 3

    - type: textarea
      id: mockups
      attributes:
          label: Mockups or Examples
          description: |
              If applicable, include mockups, diagrams, or examples of how this feature might work.
          render: markdown
          placeholder: |
              ```mermaid
              graph TD
                  A[User] --> B[Feature]
                  B --> C[Result]
              ```

    - type: textarea
      id: implementation
      attributes:
          label: Implementation Notes
          description: |
              Any technical considerations, dependencies, or implementation details you're aware of.
          placeholder: |
              - Technical considerations
              - Dependencies required
              - Breaking changes
              - Performance implications

    - type: checkboxes
      id: contribution
      attributes:
          label: Contribution
          description: Are you willing to contribute to this feature?
          options:
              - label: I'm willing to help implement this feature
              - label: I can help with testing this feature
              - label: I can help with documentation
              - label: I can provide feedback during development

    - type: checkboxes
      id: terms
      attributes:
          label: Code of Conduct
          description: By submitting this issue, you agree to follow our Code of Conduct.
          options:
              - label: I agree to follow this project's Code of Conduct
                required: true
