[package]
name = "sentinel-lib"
edition.workspace = true
version.workspace = true
authors.workspace = true
license.workspace = true
rust-version.workspace = true
description = "Shared library for SentinelD common functionality"
repository.workspace = true
homepage.workspace = true
publish = false

[dependencies]
# Core dependencies used by all components
serde.workspace = true
tracing.workspace = true
thiserror.workspace = true
anyhow.workspace = true

[dev-dependencies]
assert_cmd.workspace = true
predicates.workspace = true
