name: autofix.ci
on:
  workflow_call:
  pull_request:
  push:
    branches: [ "main" ]
permissions:
  contents: read

env:
    rust_clippy: 1.90

jobs:
    autofix:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v5
            - uses: actions/cache@v4
              with:
                  path: |
                    ~/.cargo/bin/
                    ~/.cargo/registry/index/
                    ~/.cargo/registry/cache/
                    ~/.cargo/git/db/
                    target/
                  key: autofix-${{ hashFiles('**/Cargo.lock') }}

            - name: Setup Rust
              uses: dtolnay/rust-toolchain@1.90
              with:
                  components: rustfmt, clippy

            - run: cargo clippy --fix --workspace
            - run: cargo fmt --all

            # run autofix-ci action
            - uses: autofix-ci/action@635ffb0c9798bd160680f18fd73371e355b85f27
